version: '3.4'

services:
  demoreplicationandsharding:
    image: ${DOCKER_REGISTRY-}demoreplicationandsharding
    build:
      context: .
      dockerfile: DemoReplicationAndSharding/Dockerfile
    networks:
        appNetwork:
            ipv4_address: 172.21.0.10
  postgresql_master:
    image: postgres
    container_name: postgresql_master
    restart: always
    volumes:
      - ./psqlmaster:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 228cat228
    ports:
      - "12080:5432"
      - "12081:5433"
    networks:
        appNetwork:
            ipv4_address: 172.21.0.2
  postgresql_slave:
    image: postgres
    container_name: postgresql_slave
    restart: always
    volumes:
      - ./psqlslave:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 228cat228
    ports:
      - "13080:5432"
      - "13081:5433"
    networks:
        appNetwork:
            ipv4_address: 172.21.0.3
  postgresql_slave2:
    image: postgres
    container_name: postgresql_slave2
    restart: always
    volumes:
      - ./psqlslave2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 228cat228
    ports:
      - "14080:5432"
      - "14081:5433"
    networks:
        appNetwork:
            ipv4_address: 172.21.0.4
  postgresql_shard1:
    image: postgres
    container_name: postgresql_shard1
    restart: always
    volumes:
      - ./psqlshard1:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 228cat228
    ports:
      - "15080:5432"
      - "15081:5433"
    networks:
        appNetwork:
            ipv4_address: 172.21.0.5
  postgresql_shard2:
    image: postgres
    container_name: postgresql_shard2
    restart: always
    volumes:
      - ./psqlshard2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 228cat228
    ports:
      - "16080:5432"
      - "16081:5433"
    networks:
        appNetwork:
            ipv4_address: 172.21.0.6
  postgresql_shard3:
    image: postgres
    container_name: postgresql_shard3
    restart: always
    volumes:
      - ./psqlshard3:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 228cat228
    ports:
      - "17080:5432"
      - "17081:5433"
    networks:
        appNetwork:
            ipv4_address: 172.21.0.7
networks:
    appNetwork:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.21.0.0/16"
